project_id: news-extraction-426201
extraction:
  site:
    the_guardian:
      urls:
        - https://www.theguardian.com/au
        - https://www.theguardian.com/international
        - https://www.theguardian.com/environment/climate-crisis