version: '3.8'

services:

  extraction_data_to_bigquery:
    image: "news_extraction"
    build:
      context: .
      dockerfile: news_extraction.Dockerfile
    volumes:
      - .:/app
    command: python3 src/main.py

  setting_api:
    image: "news_bigquery_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - extraction_data_to_bigquery
