name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/news-extraction.json

      - name: Set environment variable for Google Cloud credentials
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/news-extraction.json" >> $GITHUB_ENV

      - name: Install dependencies and run tests
        run: |
          pip install -r requirements-dev.txt
          pytest -v tests/
