name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"
          # service_account: 'your-service account'
          # workload_identity_provider: 'your-workload-identity-provider'

      - name: Run install requirements & tests
        run: |
          pip install -r requirements-dev.txt
          pytest -v tests/