name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '333.0.0'  # Replace with the version you need
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'kubectl'  # Specify any additional components needed

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud auth list  # Validate authentication

      - name: Run install requirements & tests
        run: |
          pip install -r requirements-dev.txt
          pytest -v tests/
