name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Authenticate to Google Cloud
        run: |
          echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > $HOME/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-service-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          # Validate credentials (example: list storage buckets)
          gcloud auth list

      - name: Run install requirements & tests
        run: |
          pip install -r requirements-dev.txt
          pytest -v tests/
